### ISSUE TITLE
[Question] How can I dump a specific module(dll) of an running process?

### ISSUE THREAD

**Issue by JerryYOJ** [hasherezade/pe-sieve#111]
I didnt find an argument for that.

**Comment by hasherezade** [comment]
Hi @JerryYOJ !
Currently it dumps only the modules that were detected as suspicious, basing on the certain criteria. Do I understand you correctly that you want to force dumping an arbitrary DLL, even if it wasn't detected? This is not supported at the moment, but I can add it in the next release.

**Comment by JerryYOJ** [comment]
Ok thanks. Good to know

**Comment by hasherezade** [comment]
@JerryYOJ - do you confirm that this is exactly the feature you was looking for? are you interested in having the force-dumping of undetected modules?

**Comment by JerryYOJ** [comment]
Yes exactly

**Comment by hasherezade** [comment]
ok, cool
