### ISSUE TITLE
some question about source code

### ISSUE THREAD

**Issue by helloobaby** [hasherezade/pe-sieve#117]
I feel that your project is very useful, and I am also puzzled by some of your algorithms.
`https://github.com/hasherezade/pe-sieve/blob/be19198456e562143e44ecc34e7d034184f4d42f/stats/stats_analyzer.cpp#L179`

Do you have more detailed information?

**Comment by hasherezade** [comment]
hi @helloobaby ,
I can understand that this part can be confusing. Those are just some magic numbers that I approximated basing on my tests, it's not something precise. Just ratios of characters that are common for particular type of content. Now it is hardcoded, but it may be replaced with some machine learning in the future.

**Comment by helloobaby** [comment]
Thank you for the explanation
