### ISSUE TITLE
Problem with VirtualQueryEx

### ISSUE THREAD

**Issue by helloobaby** [hasherezade/pe-sieve#120]
If compiled for an x86 platform and run on a host 64-bit operating system, it seems that only the working set of the 32-bit process can be correctly enumerated. And it seems that using VirtualQueryEx is not possible to completely enumerate the working set of a 64-bit process on a 32-bit process.

**Comment by helloobaby** [comment]
have to use VirtualQueryEx64

**Comment by hasherezade** [comment]
@helloobaby - yeah, using `VirtualQueryEx64` would help, but it is not the official Windows API, but a [custom extension library *wowext64*](https://github.com/rwfpl/rewolf-wow64ext/blob/master/doc/wow64ext.txt), so I decided not to use it here. I just recommend using 64-bit version of PE-sieve for a 64-bit system.
