### ISSUE TITLE
ModuleData not properly initialized

### ISSUE THREAD

**Issue by Ph3r0X1337** [hasherezade/pe-sieve#130]
The method WorkingSetScanner::scanImg(MemPageData&) constructs a local ModuleData variable with the constructor ModuleData(HANDLE, HMODULE, std::string, bool) which does not initialize the isPEBConnected field. The instance is then used with a call to modData.loadOriginal(), after that it is passed to the static method ProcessScanner::scanForHollows(HANDLE, ModuleData&, RemoteModuleData&, ProcessScanReport&). In that method a HeadersScanner object is created as local variable with a call to the HeadersScanner(HANDLE, ModuleData&, RemoteModuleData&) constructor, after that the scanRemote() method is called on the object.
After that the ModuleData field isPEBConnected is queried with the isModuleInPEBList method and gets assigned to the scanreport.
However, the field was never initialized, not even default initialized.
Am I missing something?
Also I couldn't find a Write xref to the isPEBConnected field other than the ModuleData(HANDLE, HMODULE, bool, bool) constructor...

**Comment by hasherezade** [comment]
Hi @Ph3r0X1337 !
Thank you for your report, you are right. It should be fixed now. Also, now I use only one constructor for ModuleData, it will be less error prone in case of any future updates, introducing any new fields.

**Comment by Ph3r0X1337** [comment]
Okay, but now you are setting isPEBConnected to true in your constructor call in WorkingSetScanner::scanImg(MemPageData&), although the method WorkingSetScanner::scanRemote() only calls scanImg when the module is not in the scanned modules list, hence it is probably not in the PEB. Therefore the constructor should be called with the isPEBConnected argument set to false.

**Comment by hasherezade** [comment]
yes, good catch, I am just tired today and I thought to check it in details tomorrow. But with your sharp eye I don't have to :) I see you read my code thoroughly, I appreciate.
