### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [hasherezade/pe-sieve#17]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “ProcessScanReport”](https://github.com/hasherezade/pe-sieve/blob/318f7fb8fb4747db045a0094cfbd103ce2aa713e/scanners/scan_report.h#L33 "Update candidate: Destructor for ProcessScanReport").

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/hasherezade/pe-sieve/commit/0c528c62abe6ebd19a3349e395f13f3cd497bc36 "Removed redundant null pointer check before delete").

**Comment by hasherezade** [comment]
Thanks for reporting it!
