### ISSUE TITLE
False positives or something weird?

### ISSUE THREAD

**Issue by jfariasf** [hasherezade/pe-sieve#26]
I used the software with all the processes in my machine and got a lot of warnings, so either it's severely compromised by undetected malware or there are many false positives.

Example:

> {
>  "pid" : 612,
>  "main_image_path" : "C:\\Windows\\System32\\svchost.exe",
>  "scanned" : 
>  {
>   "total" : 25,
>   "skipped" : 0,
>   "modified" : 
>   {
>    "total" : 6,
>    "hooked" : 6,
>    "replaced" : 0,
>    "detached" : 0,
>    "implanted" : 0,
>    "other" : 0
>   },
>   "errors" : 0
>  },
>  "scans" : [
>   {
>    "code_scan" : {
>     "module" : "7ffd51060000",
>     "status" : 1,
>     "patches" : 59
>    }
>   },
>   {
>    "code_scan" : {
>     "module" : "7ffd4d4b0000",
>     "status" : 1,
>     "patches" : 11
>    }
>   },
>   {
>    "code_scan" : {
>     "module" : "7ffd50320000",
>     "status" : 1,
>     "patches" : 4
>    }
>   },
>   {
>    "code_scan" : {
>     "module" : "7ffd4e4d0000",
>     "status" : 1,
>     "patches" : 58
>    }
>   },
>   {
>    "code_scan" : {
>     "module" : "7ffd50250000",
>     "status" : 1,
>     "patches" : 9
>    }
>   },
>   {
>    "code_scan" : {
>     "module" : "7ffd4d3e0000",
>     "status" : 1,
>     "patches" : 3
>    }
>   }
>  ]
> }
> 

Although... 1 file got detected, so maybe nothing or double false positive? https://www.virustotal.com/#/file-analysis/MGRiNGZlOWU0ZWVjNjM5MjliZDVhY2Q3OGRiMjY2ZjE6MTU0Nzg3MDQ5OQ==

Attaching 1 of the many many processes with warnings.

[process_612.zip](https://github.com/hasherezade/pe-sieve/files/2775138/process_612.zip)

**Comment by jfariasf** [comment]
And I don't even know what these .shc files are:

[shc.zip](https://github.com/hasherezade/pe-sieve/files/2775165/shc.zip)

**Comment by hasherezade** [comment]
hi! 
1. First of all, looking at the report I guess that you are not using the latest PE-sieve. Can you please update it to the latest [release](https://github.com/hasherezade/pe-sieve/releases) and scan it once again?
2. I see those DLLs are hooked. There are many reasons for DLLs being hooked, not all of them are malicious. PE-sieve detects the presence of a hook, but it is not meant to make a judgment if the hook is malicious or not. Read more about it on [wiki](https://github.com/hasherezade/pe-sieve/wiki). If you have an antivirus installed, it is very likely that it modifies memory of the processes in some way or the other - so, all those modifications are going to be detected by PE-sieve.
3. If you download the version 0.1.6, it will print more information about where the hook leads to. Please drop me the reports and I will tell you more about interpreting them. From what I see for now, probably your hooks are non-malicious.
