### ISSUE TITLE
Failed reconstructing the payload (Ursnif)

### ISSUE THREAD

**Issue by hasherezade** [hasherezade/pe-sieve#32]
#### Test case
[633521d921ddad8671293319f0fd9daab9a0a606887ada3ab3709027cbb1e591](https://www.virustotal.com/#/file/633521d921ddad8671293319f0fd9daab9a0a606887ada3ab3709027cbb1e591/detection)

#### Problem
The payload has a partially corrupt header (starting from file header):
![hdr_start](https://user-images.githubusercontent.com/3115348/54077797-e208f200-42bd-11e9-9ae7-7ec517dab076.png)

PE-sieve was able to find some artefacts:
![artefact](https://user-images.githubusercontent.com/3115348/54077758-44152780-42bd-11e9-9971-d3f45cda3eb2.png)
However, if failed to reconstruct the PE.

**Comment by bartblaze** [comment]
Was going to open an issue about this over the weekend, but seems like you already identified it :smile: 

Another sample if needed:
[a28b197f2cf9d82101980e302f16732fd09eb9b4760e13699a3c0d2c6cd18cc3](https://www.virustotal.com/en/file/a28b197f2cf9d82101980e302f16732fd09eb9b4760e13699a3c0d2c6cd18cc3/analysis/)

For me, pe-sieve crashes as soon as it starts scanning the memory regions. 

> OS: Windows 7 x86
> pe-sieve v0.1.6

Seems like header is corrupted and RVA can't be fetched.

**Comment by hasherezade** [comment]
@bartblaze - the crash was another issue, and I already fixed it, please check the latest builds and let me know: https://github.com/hasherezade/pe-sieve/blob/master/README.md
It will be in the official release soon.

**Comment by bartblaze** [comment]
Thanks @hasherezade, I can confirm that solved the crashing issue. (and thanks for a great tool!)

**Comment by hasherezade** [comment]
Result: the payload got shifted (to make space for the DOS header), realigned to Virtual (because of damaged raw headers) and dumped:
![result1](https://user-images.githubusercontent.com/3115348/54376866-3e845c80-4684-11e9-9e2e-cacd39b0c20a.png)
Report:
![report](https://user-images.githubusercontent.com/3115348/54376921-607ddf00-4684-11e9-8efd-4a39a7473966.png)
