### ISSUE TITLE
ntdll, user32dll

### ISSUE THREAD

**Issue by danielpe18** [hasherezade/pe-sieve#41]
after scanning a lot of processes it finds both of these dll's as suspicious and hooked into a lot of processes, guessing this is probably a false positive but just asking to make sure :)

**Comment by hasherezade** [comment]
can you share something more? reports, dumps? they could have been hooked by your AV (see [FAQ](https://github.com/hasherezade/pe-sieve/wiki/1.-FAQ)). but without seeing details it is hard to me to find what exactly happened.
