### ISSUE TITLE
Path parsing mismatch resulting in false positive

### ISSUE THREAD

**Issue by Jack-McDowell** [hasherezade/pe-sieve#51]
This issue was identified when a process load an image at "C:\Program Files (x86)\Razer\Synapse3\Service\\..\UserProcess\Razer Synapse Service Process.exe"

PE Sieve identified that this did not match the mapped image, "C:\Program Files (x86)\Razer\Synapse3\UserProcess\Razer Synapse Service Process.exe"

Consider using PathCchCanonicalize before comparing the mapped image path to the image intended to be mapped to avoid this issue.

**Comment by hasherezade** [comment]
Thank you for reporting, I will take a look as soon as I get some free time.

**Comment by hasherezade** [comment]
ok, so I checked it and unfortunately I cannot use `PathCchCanonicalize` since it is a relatively new API (introduced with Windows 8) and PE-sieve is supposed to support the old versions of Windows as well. But I will solve this problem by a manual re-implementation of this function.

**Comment by Jack-McDowell** [comment]
My bad, didn't see that it was unsupported. PathCanonicalizeA/W should work for you then

**Comment by hasherezade** [comment]
Please check if it solved the problem

**Comment by hasherezade** [comment]
I think it should work fine in the latest release, but please check and let me know: https://github.com/hasherezade/pe-sieve/releases/tag/v0.2.5

**Comment by Jack-McDowell** [comment]
I've been busy recently, but I should be able to test and get back to you next week. Thanks for fixing this!

**Comment by hasherezade** [comment]
ok, thank you! I will be waiting for your feedback.

**Comment by Jack-McDowell** [comment]
It works now! Thanks!
