### ISSUE TITLE
Could not read the remote PE 

### ISSUE THREAD

**Issue by bartblaze** [hasherezade/pe-sieve#58]
PE-sieve version: v0.2.6
Hash: ca8194e9a1232e508619269bdf9a9c71c4b76e7852d86ed18f02088229b0f7c7

Seems like PE-sieve can't read the remote PE at a specific offset - looks like an invalid address? 

FYI, this is the new Bazar malware (loader module specifically):
https://www.bleepingcomputer.com/news/security/bazarbackdoor-trickbot-gang-s-new-stealthy-network-hacking-malware/

**Comment by hasherezade** [comment]
thank you for reporting!
I will check it soon.

**Comment by hasherezade** [comment]
Can you share what was exactly the invalid result that you've got?

**Comment by hasherezade** [comment]
I run it and got valid PEs unpacked:

![unpacked_bazar](https://user-images.githubusercontent.com/3115348/80805455-5b495f80-8bb8-11ea-9133-9048af2a59b4.png)

[process_2456.zip](https://github.com/hasherezade/pe-sieve/files/4564164/process_2456.zip)

**Comment by bartblaze** [comment]
I ran it again and now they are dumped. Perhaps it was an issue with my VM. I'll keep an eye on it should it happen again and will send you the logs. Thanks for looking into it so quickly! :+1:
