### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by dnides** [hasherezade/pe-sieve#6]
Awesome project!! Thanks!! Would like to make a feature request for python bindings please!

**Comment by hasherezade** [comment]
hi! first of all I am happy that you like the project! thanks!
regarding Python bindings - this is a very good idea. I am planning to implement it once I will have a version 0.1.0 ready. stay tuned!

**Comment by dnides** [comment]
Any updates on python binding?

**Comment by hasherezade** [comment]
Sorry, I didn't have time for this yet, but it is on my TODO.
