### ISSUE TITLE
enhacement

### ISSUE THREAD

**Issue by noamlima** [hasherezade/pe-sieve#74]
you could recover process data from random generated numbers "like" or and from glitches from the electromagnetic field running though the cpu transistors no virus or malware has such knowledge you could do it though machine learning but you should sum you should get the standard deviation of every unit of artificial neuron that contains a threshold and you could generate the code your code from random seed and a correction random seed for making it compact but it contains the secret so it need to stay in a form that its consequence of a something processed or glitch trial and the binary code need to contains much zeros as posible so it reads fast and rests the cpu for some reason something there make the code weaker you should discover it ... @hasherezade @hasherezade # #72

**Comment by hasherezade** [comment]
go troll somewhere else
