### ISSUE TITLE
using UPX are scanned that hdr_modified

### ISSUE THREAD

**Issue by muse117** [hasherezade/pe-sieve#82]
The programs are scanned, it have been compressed using UPX.

**Comment by hasherezade** [comment]
Do you mean UPX packed executables are detected with a marker `hdr_modfied`? It is not a bug, but intended behavior. UPX indeed modifies the headers, and fills up the packed sections, so it should trigger PE-sieve.

**Comment by muse117** [comment]
yes, i see
