### ISSUE TITLE
When i open pe-sieve the program runs but it says on the end: press any key to continue, and it closes, what is that?

### ISSUE THREAD

**Issue by Robi1969** [hasherezade/pe-sieve#87]
When i open pe-sieve the program runs but it says on the end: press any key to continue, and it closes, what is that?
Any ideas?

**Comment by hasherezade** [comment]
Not sure what do you mean. When you run PE-sieve without any parameters it displays you the information about how to use the app, with what parameters to run it. Then you need to use those parameters to deploy the scan.
Did you ever use applications with command-line interface (CLI)?

**Comment by hasherezade** [comment]
More information you can find on project's Wiki: https://github.com/hasherezade/pe-sieve/wiki
