### ISSUE TITLE
Recognize Virtual Table hooks

### ISSUE THREAD

**Issue by hasherezade** [hasherezade/pe-sieve#88]
Example - a virtual table (not patched):

![patched_addresses0](https://user-images.githubusercontent.com/3115348/131951169-95342a38-0504-4ac7-92f8-7f67e2084e71.png)

The same table, patched:

![patched_addresses3](https://user-images.githubusercontent.com/3115348/131951246-0bd704bc-4470-43d9-97f2-2b3471d5826b.png)

Patches detected by PE-sieve:

![patched_addresses2](https://user-images.githubusercontent.com/3115348/131951225-c9f72baf-e94e-4b5d-98eb-150881473143.png)

As the above example demonstrates, the patches are properly detected by PE-sieve. However, the way in which they are reported could be improved.
Instead of a vague description `patch_<id>` and the size, a full address of the redirection should be reported, just like in the case of [inline hooks](https://github.com/hasherezade/pe-sieve/wiki/3.1.-Investigating-hooks-and-patches).

Current report:

```
21d8c;patch_0;4
21d94;patch_1;8
```

Desired report:
```
21d8c;6172C380
21d94;61721790
21d98;6172C450
```

**Comment by hasherezade** [comment]
Related commits:
b26a8047a62b460ea24757b92943137f915f71d5
5278ae61b822c17ada9d44847994f12bfb2c61d4
dd8a6f60f165faf69044993ed0fb93359d47848b

**Comment by hasherezade** [comment]
Such hooks are now displayed as `addr_replaced_<id>`:
![replaced](https://user-images.githubusercontent.com/3115348/132010957-d80d40be-7624-4763-8e70-ef205233d733.png)

**Comment by maskelihileci** [comment]
![FVCV](https://user-images.githubusercontent.com/41159853/149589589-0f74867a-8b86-4ec4-9a8f-c47fc89c4437.PNG)

Hello, am I wrong, I wonder if the vtable hook here could not detect it?


Information about hook not found in the folder?

![image](https://user-images.githubusercontent.com/41159853/149589775-f22543b9-69b8-4dbe-b0d0-02ff6437ba91.png)

**Comment by hasherezade** [comment]
@maskelihileci - can you share this sample? I will check...

**Comment by maskelihileci** [comment]
Go here from cheat engine software : KERNEL32.VirtualProtectStub 


jmp qword ptr [7FFCE1564E68]


![image](https://user-images.githubusercontent.com/41159853/149592370-da975b79-d7f8-44da-9b2e-c62fc0d6ce14.png)

![image](https://user-images.githubusercontent.com/41159853/149592453-6095e437-d34b-42b0-823f-c2faf63b303b.png)


In this way, viruses are hooked and cannot be detected.
This is because there is no change to the assembly code

When it said it detected the vtable hook I thought it might detect it.

**Comment by hasherezade** [comment]
@maskelihileci - ok, I reproduced it. this is actually an IAT hook, not VTable hook. those are usually detected with a parameter `/iat [option]` - but I see it is not detected this time, so there is a bug. thank you for your report, it will be fixed soon.

**Comment by hasherezade** [comment]
BTW - would you like to create a new issue for this? by this way you can keep track on the progress, and get notified when it is fixed

**Comment by maskelihileci** [comment]
Thanks, I opened the issue.

**Comment by hasherezade** [comment]
@maskelihileci - thank you!
