### ISSUE TITLE
Logo proposal for PE-SIEVE

### ISSUE THREAD

**Issue by baranpirincal** [hasherezade/pe-sieve#9]
Hello! I designed a logo for PE-SIEVE. I hope you like it. 
I'm waiting your feedbacks for sending original/editable/.png version of logo design or for improve it.
I can change colors or add something you wanted on design! Have a good day!

![bunuat1235](https://user-images.githubusercontent.com/37786733/38471956-0dab736e-3b81-11e8-8677-cc07fa0effd1.jpg)
![bunudat22452](https://user-images.githubusercontent.com/37786733/38471958-1357aa80-3b81-11e8-8f4d-a44def0f24aa.jpg)

**Comment by baranpirincal** [comment]
Of course, we can see it together. I will do it with green&red colors as soon as possible

**Comment by baranpirincal** [comment]
Here, I used different green and red tones and made in 2 versions. What do you think? It's your turn
![untitled-1](https://user-images.githubusercontent.com/37786733/38472286-689b3232-3b86-11e8-8031-7418c68e62d9.jpg)

**Comment by hasherezade** [comment]
nice! I like the fist one the most (the upper left corner, darker tones)
![a1](https://user-images.githubusercontent.com/3115348/38472412-f6737c56-3b7f-11e8-8a25-e9b4ce9cf95d.png)

**Comment by baranpirincal** [comment]
@hasherezade I created a pull-request, could you please check it? I uploaded source files and .png format both. Thanks in advance.

**Comment by hasherezade** [comment]
Thank you! if possible, could you please generate an icon also?

**Comment by baranpirincal** [comment]
with which size you prefer?

**Comment by hasherezade** [comment]
Best would be an icon with multiple sizes embedded inside, so that it will scale smoothly. From 128x128, then 64x64, 32x32 and the smallest 16x16.

**Comment by hasherezade** [comment]
I mean ICO format.

**Comment by baranpirincal** [comment]
It is done. Could you please check it?

**Comment by hasherezade** [comment]
thank you! but few remarks: 
1) I forgot 48x48 size.
2) when I mean scaling it I not necessarily mean scaling literally. the smaller versions of icons usually have lesser details than their bigger equivalents, so that they will look nice. for example, rather than having many small boxes that are getting very blurred in the small version, it could have lesser boxes but bigger.
3) could you merge those icons into one with multiple sizes? just like it is done in PE-bear
![icon_sizes](https://user-images.githubusercontent.com/3115348/38473262-6a22b768-3b8d-11e8-9dcf-3e4d1e3f749b.png)

**Comment by baranpirincal** [comment]
I scaled the logo design as you said and merged it with multiple sizes. Could you check again? 
It will looks like:

![ghgfh](https://user-images.githubusercontent.com/37786733/38473489-65b6689e-3b99-11e8-8fd3-7f5d2c6f8a55.jpg)

**Comment by baranpirincal** [comment]
If you want that colors to come up regularly I can make like this, according to your choice;

![hh](https://user-images.githubusercontent.com/37786733/38473529-1587b39a-3b9a-11e8-8a6b-29f393088a83.png)

**Comment by hasherezade** [comment]
hmm, is not exactly what I meant. I like the original logo with many details. but when it is scaled i.e. to 16x16 it does not look good, because all is blurred. so, what I meant is to differentiate a level of details to fit the particular resolution. then, merge the multiple designs into a one ICO file.

**Comment by hasherezade** [comment]
see how I did it in PE-bear - the big logo has "PE" written inside. but the smaller version does not, because it would not look good.

**Comment by baranpirincal** [comment]
I'm sorry I confused. "to differentiate a level of details to fit the particular resolution". As you said I reduced the details of logo design with making squares bigger. Otherwise, how can I differentiate the details? :(

**Comment by baranpirincal** [comment]
with making magnifying glass bigger? or playing spaces between squares?

**Comment by hasherezade** [comment]
and what I mean is something like this:
![different](https://user-images.githubusercontent.com/3115348/38473747-29b2cf94-3b95-11e8-9431-b0b01bd0154d.png)

**Comment by hasherezade** [comment]
I like this one a lot. merging it should be not a problem. if you don't have the tools capable of generating an icon from different images, then you can leave the merging to me. just commit the set of the icons and I will do the rest. thanks!

**Comment by baranpirincal** [comment]
You're welcome. I added all logo icons and created pull-request, have a nice day!

**Comment by hasherezade** [comment]
Thanks a lot! You too!

**Comment by hasherezade** [comment]
Check the latest builds! They are with your icon :)

**Comment by hasherezade** [comment]
Also, I changed the banner so that it will fit to the logo. What do you think?
![banner](https://user-images.githubusercontent.com/3115348/38504991-6f7e2704-3c16-11e8-8736-33cafa452d5b.png)

**Comment by baranpirincal** [comment]
Definetly better. The project has it's own kind of a visual identity now.

**Comment by hasherezade** [comment]
The full new theme after some improvements:
![theme](https://user-images.githubusercontent.com/3115348/38512759-6797daa6-3c2c-11e8-89c1-bb4c1baafbb4.png)

I think it is done. Thanks!
