### ISSUE TITLE
leak?

### ISSUE THREAD

**Issue by core-c** [hasherezade/pe-sieve#95]
Hi there, Ron here.
Jak sie masz?
Great work hasherezade.. girl power.

### scan own working set
When your pe-sieve (static lib) is used to scan the process it is embedded in (current process), then there is that line in **scanRemote()** that excludes the own working set from being scanned. Can there be an easier way to also include the own working set in the scan? (than to comment out some code).

### memory leak?
When a scan is done at regular intervals (_some_ seconds), there is an increase in memory consumption.
In **collectExecutableSections()**, iterating all the found sections, at some point a new PeSection class is instantiated: `remoteSec = new PeSection`. But there are cases where remoteSec is discarded (the for-loop continued, or `sections[i] = remoteSec` not executed).
Also the check `if (sec_count == 0)` has the possibility to discard remoteSec.
The allocated PeSection memory of the discarded remoteSec instances is never freed.  i think..
If i `free_unaligned(remoteSec->loadedSection)` for any discarded remoteSec, the memory consumption is stable.

### Documentation completeness
On the webpage _How to add PE sieve to your Visual Studio project_ you could mention to also add other needed libs, like:
**Library Directories (to the directory where the libpeconv.lib is)**

Thank you..

**Comment by hasherezade** [comment]
hi! thank you very much for your remarks! I will investigate the possible leak, and fix it soon!

**Comment by hasherezade** [comment]
my last commit should fix the problem. please check it out and let me know.

**Comment by core-c** [comment]
Thanks,

Have you ever tried to use OpenMP for a project like pe-sieve?
I bet you can speed up program-execution quite a bit.

I am helping out someone who wants to create an anticheat for a game.
To help him, i needed to dive into this code. It was someone else who pointed me at your github.
You have already coded much more than i did for our project. But the code i made so far works, and i had played some with OpenMP.
With just a single line addition, in my MSVS project, i was able to scan the modules of a process on all the cores. That resulted in a big performance boost.
If they want speed?..  It’s worth a try

Greetings,
Ron.

**Comment by core-c** [comment]
Quote: " Yep, and it works very well!”

That was quick!
Na zdrowie

Thanks again.

**Comment by hasherezade** [comment]
I am glad it is fixed now!
Regarding the documentation - I added a separate section about [adding PE-sieve static library to a Visual Studio project](https://github.com/hasherezade/pe-sieve/wiki/2.1.-How-to-add-PE-sieve-to-your-Visual-Studio-project#adding-pe-sieve-static-library-version) - in which case you need to add additional libraries.
please check it out and let me know your thoughts!

**Comment by core-c** [comment]
Yes, it’s fixed.  Woohoo.
Your code is pretty organized, and there are just a few locations where memory is allocated, so it was easy to find the cause of the problem.. just a few clicks away.
Also, your functions are all short, and that makes it much easier to read the code.

The documentation seems complete. This should now make things clear for any novice.

Thanks for your quick replies and actions.
Where is the ‘donate’ button?

**Comment by hasherezade** [comment]
I appreciate your contribution! The release with the fix is out: https://github.com/hasherezade/pe-sieve/releases/

**Comment by hasherezade** [comment]
Since the leak is resolved, I guess we can close this issue. Other ideas for improvements can be discussed here: https://github.com/hasherezade/pe-sieve/discussions - or in separate issues.
