### ISSUE TITLE
KERNEL32.VirtualProtectStub IAT hook Does not detect

### ISSUE THREAD

**Issue by maskelihileci** [hasherezade/pe-sieve#98]
![149589589-0f74867a-8b86-4ec4-9a8f-c47fc89c4437](https://user-images.githubusercontent.com/41159853/149598390-389defb7-4746-43ba-8244-e649a2d3a85e.png)
![149589775-f22543b9-69b8-4dbe-b0d0-02ff6437ba91](https://user-images.githubusercontent.com/41159853/149599131-5f507950-cce4-4043-a1c2-7271f742136f.png)

**Comment by maskelihileci** [comment]
Problem solved, thanks again for your attention.

**Comment by hasherezade** [comment]
@maskelihileci - check out the new release: https://github.com/hasherezade/pe-sieve/releases/tag/v0.3.3
